export { default as Category } from './Category'
export { default as StoryTxtImg } from './StoryTxtImg'
export { default as StoryTxt } from './StoryTxt'
export { default as Home } from './Home'
export { default as Inputs } from './Inputs'
export { default as UserSettings } from './UserSettings'
export { default as Loading } from './Loading'